[package]
name = "fusor-workers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fusor-core = { workspace = true, features = ["dom"] }
fusor-components = { workspace = true, features = ["browser"] }
fusor-async = { workspace = true, features = ["browser"] }
fusor-worker.workspace = true
wasm-bindgen.workspace = true

[build-dependencies]
fusor-build.workspace = true

[package.metadata.fusor]
entry = "web/index.html"

[lints]
workspace = true
