//! Node-free module extraction and editor declarations. Bundling is host tooling.
use crate::{
    JavaScriptModule,
    app::{JavaScriptArtifact, SourceError},
};
use std::{
    fs,
    path::{Path, PathBuf},
};
use syn::{GenericArgument, Item, PathArguments, Type};
type Result<T> = std::result::Result<T, crate::BuildError>;

fn typescript(ty: &Type) -> Option<String> {
    let Type::Path(path) = ty else {
        return None;
    };
    let segment = path.path.segments.last()?;
    Some(match segment.ident.to_string().as_str() {
        "bool" => "boolean".into(),
        "String" => "string".into(),
        "f64" | "i32" | "u32" => "number".into(),
        "JsValue" => "unknown".into(),
        "Option" | "Vec" | "Signal" => {
            let PathArguments::AngleBracketed(args) = &segment.arguments else {
                return None;
            };
            let Some(GenericArgument::Type(inner)) = args.args.first() else {
                return None;
            };
            let inner = typescript(inner)?;
            match segment.ident.to_string().as_str() {
                "Option" => format!("({inner} | null)"),
                "Vec" => format!("Array<{inner}>"),
                _ => inner,
            }
        }
        _ => return None,
    })
}
fn field_declarations(item: &syn::ItemStruct) -> Result<String> {
    let mut fields = String::new();
    for field in &item.fields {
        if !field
            .attrs
            .iter()
            .any(|attribute| attribute.path().is_ident("js"))
        {
            continue;
        }
        let name = field
            .ident
            .as_ref()
            .ok_or("JavaScript inputs require named fields")?;
        let ty =
            typescript(&field.ty).ok_or("cannot discover the TypeScript type of a #[js] field")?;
        fields.push_str(&format!(
            "  readonly {}: ReadonlyInput<{ty}>;\n",
            name.to_string().trim_start_matches("r#")
        ));
    }
    Ok(fields)
}

fn derives_js_inputs(attributes: &[syn::Attribute]) -> Result<bool> {
    for attribute in attributes
        .iter()
        .filter(|attribute| attribute.path().is_ident("derive"))
    {
        let derives = attribute.parse_args_with(
            syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
        )?;
        if derives.iter().any(|path| {
            path.segments
                .last()
                .is_some_and(|part| part.ident == "JsInputs")
        }) {
            return Ok(true);
        }
    }
    Ok(false)
}

fn declarations(
    items: &[Item],
    component: &str,
    declared: &mut std::collections::BTreeMap<String, String>,
) -> Result<bool> {
    let mut found = false;
    for item in items {
        if let Item::Mod(module) = item {
            if let Some((_, items)) = &module.content {
                found |= declarations(items, component, declared)?;
            }
        }
        let Item::Struct(item) = item else {
            continue;
        };
        let name = item.ident.to_string();
        found |= name == component;
        if derives_js_inputs(&item.attrs)?
            && declared
                .insert(name.clone(), field_declarations(item)?)
                .is_some()
        {
            return Err(format!("ambiguous JavaScript input declaration for {name}").into());
        }
    }
    Ok(found)
}

fn declaration(rust: &str, component: &str) -> Result<String> {
    let mut result = String::from(
        "// Generated by Fusor. Rebuild after changing #[js] fields.\nexport interface ReadonlyInput<T> { get(): T; subscribe(callback: (value: T) => void): () => void; }\n",
    );
    let component = component.rsplit("::").next().unwrap_or(component).trim();
    let mut declared = std::collections::BTreeMap::new();
    let file = syn::parse_file(rust)?;
    let found = declarations(&file.items, component, &mut declared)?;
    for (name, fields) in &declared {
        result.push_str(&format!("export interface {name}Inputs {{\n{fields}}}\nexport type {name}MountContext = ComponentMountContext<{name}Inputs>;\n"));
    }
    let input = if declared.contains_key(component) {
        format!("{component}Inputs")
    } else if found {
        "Record<string, never>".into()
    } else if declared.is_empty() {
        return Err(format!("cannot discover JavaScript inputs for {component}; keep its struct and template! in the same Rust source").into());
    } else {
        // Custom App factories require Rust inference; expose their real derived shapes.
        declared
            .keys()
            .map(|name| format!("{name}Inputs"))
            .collect::<Vec<_>>()
            .join(" | ")
    };
    result.push_str(&format!("export type Inputs = {input};\n"));
    result.push_str("export interface ComponentMountContext<I> { readonly root: Element; readonly signal: AbortSignal; readonly inputs: I; onCleanup(callback: () => void): void; }\nexport type MountContext = ComponentMountContext<Inputs>;\nexport type OnMount = (context: MountContext) => void | (() => void);\n");
    Ok(result)
}

fn contains_template(items: &[Item], relative: &str) -> bool {
    items.iter().any(|item| match item {
        Item::Mod(module) => module
            .content
            .as_ref()
            .is_some_and(|(_, items)| contains_template(items, relative)),
        Item::Macro(item) => {
            item.mac
                .path
                .segments
                .last()
                .is_some_and(|segment| segment.ident == "template")
                && syn::parse2::<syn::LitStr>(item.mac.tokens.clone())
                    .is_ok_and(|literal| literal.value() == relative)
        }
        _ => false,
    })
}

fn native_rust(package: &Path, html: &Path) -> Result<Option<PathBuf>> {
    // `template!` paths use `/` on every platform, so compare components.
    let Some(relative) = html.strip_prefix(package).ok().and_then(|path| {
        path.components()
            .map(|component| component.as_os_str().to_str())
            .collect::<Option<Vec<_>>>()
            .map(|parts| parts.join("/"))
    }) else {
        return Ok(None);
    };
    fn visit(directory: &Path, relative: &str) -> Result<Option<PathBuf>> {
        if !directory.is_dir() {
            return Ok(None);
        }
        let mut entries = fs::read_dir(directory)?.collect::<std::io::Result<Vec<_>>>()?;
        entries.sort_by_key(|entry| entry.path());
        for entry in entries {
            let path = entry.path();
            if entry.file_type()?.is_symlink() {
                continue;
            }
            if path.is_dir() {
                if let Some(path) = visit(&path, relative)? {
                    return Ok(Some(path));
                }
            } else if path.extension().is_some_and(|ext| ext == "rs") {
                let source = fs::read_to_string(&path)?;
                let file = syn::parse_file(&source)
                    .map_err(|error| SourceError::new(&path, &error).with_cause(error))?;
                if contains_template(&file.items, relative) {
                    return Ok(Some(path));
                }
            }
        }
        Ok(None)
    }
    visit(&package.join("src"), &relative)
}

/// A component module, checked while its source compiles and written afterwards.
pub(crate) struct PlannedModule {
    pub(crate) artifact: JavaScriptArtifact,
    /// An inline module's body, written to `artifact.path`.
    inline: Option<String>,
    declaration: String,
}

/// Resolve and check a source's component modules without writing anything.
pub(crate) fn plan(
    package: &Path,
    output: &Path,
    html: &Path,
    page: &crate::Page,
    external: Option<&Path>,
) -> Result<Vec<PlannedModule>> {
    if page.javascript.is_empty() {
        return Ok(Vec::new());
    }
    let native = if external.is_none() {
        native_rust(package, html)?
    } else {
        None
    };
    let rust_source = external.map(Path::to_owned).or(native);
    let rust = rust_source
        .as_ref()
        .map(fs::read_to_string)
        .transpose()?
        .unwrap_or_else(|| page.rust.clone());
    let directory = output.join("fusor_javascript");
    let source_name = file_name_part(&html.strip_prefix(package)?.to_string_lossy(), false);
    page.javascript
        .iter()
        .map(|module| {
            let component_name = file_name_part(&module.component, true);
            let path = match &module.src {
                Some(src) => module_source(package, html, module, src)?,
                None => directory.join(format!("{source_name}-{component_name}.js")),
            };
            let declaration_name = format!("{source_name}-{component_name}.d.ts");
            Ok(PlannedModule {
                artifact: JavaScriptArtifact {
                    id: module.id.clone(),
                    path,
                    source: html.to_owned(),
                    line: module.line,
                    column: module.column,
                    component: module.component.clone(),
                    inline: module.src.is_none(),
                    declaration: directory.join(&declaration_name),
                    declaration_name,
                    rust_source: rust_source.clone(),
                },
                inline: module.src.is_none().then(|| module.content.clone()),
                declaration: declaration(&rust, &module.component).map_err(|error| {
                    SourceError::at(html, module.line, module.column, &error).with_cause(error)
                })?,
            })
        })
        .collect()
}

pub(crate) fn write(modules: &[PlannedModule]) -> Result<()> {
    for module in modules {
        let declaration = &module.artifact.declaration;
        fs::create_dir_all(declaration.parent().expect("declaration directory"))?;
        if let Some(content) = &module.inline {
            fs::write(&module.artifact.path, content)?;
        }
        fs::write(declaration, &module.declaration)?;
    }
    Ok(())
}

fn module_source(
    package: &Path,
    html: &Path,
    module: &JavaScriptModule,
    src: &str,
) -> Result<PathBuf> {
    let path = html
        .parent()
        .expect("HTML parent")
        .join(src)
        .canonicalize()
        .map_err(|error| {
            SourceError::at(
                html,
                module.line,
                module.column,
                format!("component JavaScript source {src}: {error}"),
            )
            .with_cause(error)
        })?;
    let supported = path
        .extension()
        .is_some_and(|extension| extension == "js" || extension == "mjs" || extension == "ts");
    if !path.starts_with(package) || !supported {
        return Err(SourceError::at(
            html,
            module.line,
            module.column,
            "component module src must identify a .js, .mjs, or .ts file inside this package",
        )
        .into());
    }
    Ok(path)
}

/// Replace characters that are unsafe in generated file names with `-`.
fn file_name_part(text: &str, keep_underscore: bool) -> String {
    text.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || keep_underscore && character == '_' {
                character
            } else {
                '-'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn declarations_match_only_marked_supported_fields() {
        let source = "#[derive(JsInputs)] struct Scene { #[js] speed: Signal<f64>, private: Signal<String>, #[js] values: Signal<Option<Vec<i32>>>, #[js] handle: Signal<JsValue> }";
        let output = declaration(source, "Scene").unwrap();
        assert!(output.contains("speed: ReadonlyInput<number>"));
        assert!(output.contains("values: ReadonlyInput<(Array<number> | null)>"));
        assert!(output.contains("handle: ReadonlyInput<unknown>"));
        assert!(!output.contains("private"));
    }
}
